name: Go

on:
  schedule:
    - cron: '45 14 * * *'  
  push:
    branches: [ master ]

jobs:
  build:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run go app
      run: go run main.go
      env:
        SECRET: $ {{ secrets.SECRET }}
        TOKEN: ${{ secrets.TOKEN }}
        
